Add NSS endpoints for ECH interop
xvzcf/tls-interop-runner pull request #25
Opened 2021-01-27 23:53 UTC by kjacobs-moz

This currently works for `ech-accept` with an NSS client and cloudflare-go server. 

For the other direction, I'll need to land a change to [selfserv.c](https://searchfox.org/mozilla-central/source/security/nss/cmd/selfserv/selfserv.c#1967) to consume the PKCS8-format HPKE keypair. With that change applied, connection succeeds from cloudflare-go to NSS.

2021-01-31 18:54 UTC, cjpatton commented
Is this ready to review, @kjacobs-moz?

2021-02-01 00:14 UTC, kjacobs-moz commented
> Is this ready to review, @kjacobs-moz?

Yes, the NSS change has landed.

2021-02-02 00:09 UTC, cjpatton requested changes
This looks great! Just a few minor nits and one ask (see inline comments).

Also, a question: The ECH draft does not specify how to format secret keys. Would you endorse PKCS#8 as a format for our purposes here? In other words, should we modify `util.go` to output an ECHConfigs and, separately, an the corresponding PKCS#8-formatted key pair? (See #17.)

2021-02-02 00:09 UTC, cjpatton commented on impl-endpoints/nss/ech_key_converter.py
> +        ech_keys = base64.b64decode(f.read(), None, True)
Suggest s/ech_keys/ech_keypair/. ech_keys sounds like it's a sequence of ECHKey structures.

2021-02-02 00:09 UTC, cjpatton commented on impl-endpoints/nss/run_endpoint.sh
> +	openssl pkcs12 -export -out nss_testdata/client-facing.pfx -name client-facing.com -inkey testdata/client-facing.key -in testdata/client-facing.crt -passout pass:"$P12_PASS"
nit: Align these lines with the indentation of the block.

2021-02-02 00:09 UTC, cjpatton commented on impl-endpoints/nss/ech_key_converter.py
> +pkcs8_oid = b"\xa1\x23\x03\x21\x00"
How does NSS Interpret these values? Are they specific to X25519? If so, please add a comment explaining that they are.

2021-02-02 00:09 UTC, cjpatton commented on cmd/util/make.go
> +			OrganizationalUnit: []string{outPath},
<3

2021-02-02 02:42 UTC, cjpatton commented
> For the other direction, I'll need to land a change to [selfserv.c](https://searchfox.org/mozilla-central/source/security/nss/cmd/selfserv/selfserv.c#1967) to consume the PKCS8-format HPKE keypair. With that change applied, connection succeeds from cloudflare-go to NSS.

FWIW, cloudflare-go client -> nss server works correctly with the existing conversion script.

2021-02-02 13:38 UTC, chris-wood approved these changes
LGTM pending @cjpatton's suggestions for the key conversion script.

2021-02-02 19:08 UTC, cjpatton commented
> LGTM pending @cjpatton's suggestions for the key conversion script.

I'm happy to merge without the conversion and get back to it later.

2021-02-02 19:09 UTC, chris-wood commented
Yeah, same. I was referring to the documentation suggestions. But even those I'd be fine without.

2021-02-02 19:22 UTC, kjacobs-moz commented
> > LGTM pending @cjpatton's suggestions for the key conversion script.
> 
> I'm happy to merge without the conversion and get back to it later.

Thanks for the reviews.

Unfortunately, I'm not going to have time in the immediate future to rewrite it in Go, but I would definitely support PKCS8-formatting the ECH/HPKE keypair rather than storing the raw private key, which some libraries may not be able to import easily. NSS is one such library, and doing it outside of NSS/selfserv avoids having to write a second ECHConfigs parser at the application level. With that change, we could remove the script entirely, but it might be worth waiting to see if other libraries have an opinion.

Another option is to output two formats from util.go.

2021-02-02 20:54 UTC, cjpatton approved these changes
LGTM. Pleas squash the last commit before merging.

2021-02-02 20:55 UTC, cjpatton commented
> LGTM. Pleas squash the last commit before merging.

Oops, scratch that. Commits look good. I'm merging now.

2021-02-02 20:55 UTC, merged